cargo-features = ["per-package-target", "profile-rustflags"]

[package]
name = "mnemos-x86_64-bootimager"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
camino = "1"
# cargo_metadata = "0.18.1"
# used for UEFI booting in QEMU
ovmf-prebuilt = "0.1.0-alpha.1"
clap = { version = "4.5", features = ["derive", "env"] }
bootloader = "0.11"
bootloader-boot-config = "0.11.3"
escargot = "0.5"
tracing = "0.1"
tracing-subscriber = "0.3"
