[package]
name = "mq-pro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# mnemos drivers
drivers = { path = "../../drivers" }

# rust-embedded crates
riscv = "0.10"
riscv-rt = "0.11.0"
d1-pac = "0.0.31"
embedded-hal = "0.2.7"

[dependencies.futures]
version = "0.3.21"
default-features = false
features = ["async-await"]

# kernel
[dependencies.mnemos]
path = "../../../../source/kernel"
default-features = false
features = ["tracing-02"]