[workspace]
resolver = "2"
members = [
    "."
]

[package]
name = "mnemos-d1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

### bin targets for each board ###
[lib]
test = false
bench = false

[[bin]]
name = "lichee-rv"
test = false
bench = false

[[bin]]
name = "mq-pro"
test = false
bench = false

### deps ###

[dependencies]
# D1 core
mnemos-d1-core = { path = "../core" }

# rust-embedded crates
riscv = "0.10"
riscv-rt = "0.11.0"
d1-pac = "0.0.31"
embedded-hal = "0.2.7"

[dependencies.futures]
version = "0.3.21"
default-features = false
features = ["async-await"]

# kernel
[dependencies.mnemos]
path = "../../../source/kernel"
default-features = false
features = ["tracing-02"]

# tracing 0.2
[dependencies.tracing]
git = "https://github.com/tokio-rs/tracing"
# branch = "master"
features = ["attributes"]
default-features = false

[dependencies.embedded-graphics]
version = "0.7.1"

[dependencies.mnemos-beepy]
path = "../../beepy"

### patches ###

[patch.crates-io.maitake]
git = "https://github.com/hawkw/mycelium.git"
rev = "101a4abaa19afdd131b334a16d92c9fb4909c064"

[patch.crates-io.mycelium-util]
git = "https://github.com/hawkw/mycelium.git"
rev = "101a4abaa19afdd131b334a16d92c9fb4909c064"

# Use the `mycelium-bitfield` crate from the Mycelium monorepo rather than
# crates.io.
# NOTE: this patch, unlike the patches for `maitake` and `mycelium-util`, (which
# are unpublished), is not *strictly* necessary, as `mycelium-bitfield` *is*
# published to crates.io. However, we may as well depend on the git version,
# since it's already in our dependency tree as a transitive dep of `maitake` ---
# having both a Git dep and a crates.io dep seems unfortunate.
[patch.crates-io.mycelium-bitfield]
git = "https://github.com/hawkw/mycelium.git"
rev = "101a4abaa19afdd131b334a16d92c9fb4909c064"

[patch.crates-io.cordyceps]
git = "https://github.com/hawkw/mycelium.git"
rev = "101a4abaa19afdd131b334a16d92c9fb4909c064"

[patch.crates-io.mnemos-alloc]
path = "../../../source/alloc"

# NOTE: keep this patch in sync with the one in the main kernel workspace!
[patch.crates-io.bbq10kbd]
git = "https://github.com/hawkw/bbq10kbd"
branch = "eliza/async"
