[workspace]
resolver = "2"
members = [
    "."
]

[package]
name = "mnemos-wifi-buddy"
version = "0.1.0"
authors = [
    "Eliza Weisman <eliza@elizas.website>",
    "James Munns <james@onevariable.com>",
]
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "./README.md"

[profile.release]
# it turns out that we basically just "can't" build in debug mode (or our code
# will fault), so just build in release mode all the time but keep debug
# symbols.
debug = true

[lib]
test = false
bench = false

[[bin]]
name = "qtpy"
test = false
bench = false

[[bin]]
name = "xiao"
test = false
bench = false


[dependencies.esp32c3-hal]
version = "0.10.0"
features = [
    "rt",
    "vectored",
]

[dependencies.esp-backtrace]
version = "0.7.0"
features = ["esp32c3", "panic-handler", "exception-handler", "print-uart"]

# kernel
[dependencies.mnemos]
path = "../../../source/kernel"
features = ["serial-trace"]

[dependencies.mnemos-esp32c3-core]
path = "../core"

[dependencies.tracing]
version = "0.1.37"
# branch = "master"
features = ["attributes"]
default-features = false

[dependencies.portable-atomic]
version = "1.4"
default-features = false
features = ["critical-section"]

### patches ###

[patch.crates-io.maitake]
git = "https://github.com/hawkw/mycelium.git"
rev = "101a4abaa19afdd131b334a16d92c9fb4909c064"

[patch.crates-io.mycelium-util]
git = "https://github.com/hawkw/mycelium.git"
rev = "101a4abaa19afdd131b334a16d92c9fb4909c064"

# Use the `mycelium-bitfield` crate from the Mycelium monorepo rather than
# crates.io.
# NOTE: this patch, unlike the patches for `maitake` and `mycelium-util`, (which
# are unpublished), is not *strictly* necessary, as `mycelium-bitfield` *is*
# published to crates.io. However, we may as well depend on the git version,
# since it's already in our dependency tree as a transitive dep of `maitake` ---
# having both a Git dep and a crates.io dep seems unfortunate.
[patch.crates-io.mycelium-bitfield]
git = "https://github.com/hawkw/mycelium.git"
rev = "101a4abaa19afdd131b334a16d92c9fb4909c064"

[patch.crates-io.cordyceps]
git = "https://github.com/hawkw/mycelium.git"
rev = "101a4abaa19afdd131b334a16d92c9fb4909c064"

[patch.crates-io.mnemos-alloc]
path = "../../../source/alloc"