[package]
name = "mnemos-d1-core"
version = "0.1.0"
edition = "2021"
description = """
A hardware abstraction library for the Allwinner D1, targeted
at use in the mnemos operating system.
"""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
d1-pac = "0.0.31"
critical-section = "1.1.1"

# kernel
[dependencies.mnemos]
path = "../../../source/kernel"
default-features = false

[dependencies.tracing]
version = "0.1.37"
features = ["attributes"]
default-features = false

[dependencies.embedded-graphics]
version = "0.7.1"

[dependencies.futures]
version = "0.3.21"
features = ["async-await"]
default-features = false

[dependencies.riscv]
version = "0.10"
# disable the `rt` feature, which enables a `critical-section` impl that
# conflicts with others in the workspace.
default-features = false