[package]
name = "mnemos-d1-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
riscv = "0.10"
riscv-rt = "0.11.0"
d1-pac = "0.0.31"

# kernel
[dependencies.mnemos]
path = "../../../source/kernel"
default-features = false
features = ["tracing-02"]